# compose file for testing papagei
#
# This compose stack is used to start all necessary services to test papagei,
# which includes hamster, chamaeleon, fuchs and fuchs-db. They are pulled
# from DockerHub.
#
# usage:
# - starting:
#   docker compose up -d --pull always
# - stopping:
#   docker compose down
#
# this compose stack starts:
# - hamster
# - chamaeleon
# - fuchs
# - fuchs_db (database for fuchs)
# - krakend (gateway)
#
# papagei will be available under localhost:8000/index.html


services:
  hamster:
    image: balindner/hamster
    volumes:
    - type: bind
      source: .
      target: /app/files
      read_only: true
  chamaeleon:
    image: balindner/chamaeleon
  fuchs:
    image: balindner/fuchs
    environment:
      DB_NAME: fuchs_db
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_HOST: fuchs-db
      URL_HAMSTER: http://hamster:8000
      URL_CHAMAELEON: http://chamaeleon:8000
  fuchs-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fuchs_db
    volumes:
    - type: bind
      source: ../fuchs/init.sql
      target: /docker-entrypoint-initdb.d/init.sql
  traefik:
    image: traefik
    volumes:
    - type: bind
      source: ./traefik
      target: /etc/traefik
      read_only: true
    ports:
    - 127.0.0.1:8000:8000
