[http.routers.fuchs]
rule = "PathPrefix(`/notes`)"
service = "fuchs"

[http.routers.hamster]
priority = -1
service = "hamster"

[http.routers.api]
rule = "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
service = "api@internal"

[http.services.fuchs]
url = "fuchs:8000"

[http.services.hamster]
url = "hamster:8000"