name: chamaeleon

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_chamaeleon:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./chamaeleon
      run: cargo build --verbose
    - name: Run Unit Test
      working-directory: ./chamaeleon
      run: cargo test --verbose
    - name: Run Application Test
      working-directory: ./chamaeleon
      run: ./test.sh
    - name: docker build
      working-directory: ./chamaeleon
      run: docker build -t myapp:latest .
    - name: Run container to test
      working-directory: ./chamaeleon
      run: |
        # Run the container and output logs
        docker run --rm myapp:latest
        docker stop myapp:latest -t 3
      
  

