name: chamaeleon

on:
  workflow_call:  # allow this workflow to be called from other workflows
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_chamaeleon:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: v0-rust
        workspaces: "hamster -> target
    - name: Build
      working-directory: ./chamaeleon
      run: cargo build --verbose
    - name: Run Unit Test
      working-directory: ./chamaeleon
      run: cargo test --verbose
    - name: Run Application Test
      working-directory: ./chamaeleon
      run: ./test.sh
    - name: docker build
      working-directory: ./chamaeleon
      run: docker build -t chamaeleon:test .
    - name: Run container to test
      working-directory: ./chamaeleon
      run: ./test.sh docker
      
  

