name: chamaeleon

on:
  workflow_call:  # allow this workflow to be called from other workflows
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_duplicate:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: "same_content_newer"
        paths:
        - "chamaeleon/**"
        - "Cargo.toml"
        - "Cargo.lock"

  build_chamaeleon:
    runs-on: ubuntu-latest
    needs: check_duplicate
    if: needs.check_duplicate.outputs.should_skip != 'true'
    steps:
    - uses: actions/checkout@v4
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: shared
    - name: Build
      run: cargo build --verbose -p chamaeleon
    - name: Run Unit Test
      run: cargo test --verbose -p chamaeleon
    - name: Run Application Test
      run: ./chamaeleon/test.sh
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: "./chamaeleon/Dockerfile"
        push: false
        load: true
        tags: chamaeleon:test
        cache-from: type=gha,scope=chamaeleon
        cache-to: type=gha,mode=max,scope=chamaeleon
    - name: Run container to test
      working-directory: ./chamaeleon
      run: ./test.sh docker
      
  

