# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: fuchs

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_build_hamster:
    uses: ./.github/workflows/hamster.yml  # use the callable tests job to run tests and build a new docker immage
    
  lint_and_test_fuchs:
    runs-on: ubuntu-latest
    needs: test_build_hamster
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
      with:
        src: "./fuchs"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: "./hamster/Dockerfile"
        push: false
        load: true
        tags: hamster:test
        cache-from: type=gha,scope=hamster
    - name: Run UnitTests
      run: |
        docker compose -f fuchs/docker-compose.yml up &
        sleep 1
        python -m unittest ./fuchs/tests/test_database.py ./fuchs/tests/test_main.py
