name: hamster

on:
  workflow_call:  # allow this workflow to be called from other workflows
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_hamster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: shared
        workspaces: |
          hamster -> target
          chamaeleon -> target
        # hamster and chamaeleon share a cache -> only chamaeleon stores to cache to avoid conflicts
        save-if: "false"
    - name: Build
      working-directory: ./hamster
      run: cargo build --verbose
    - name: Run Application Test
      working-directory: ./hamster
      run: ./test.sh
    - name: Expose GitHub Runtime # needed for docker build with cache
      uses: crazy-max/ghaction-github-runtime@v3
    - name: docker build
      working-directory: ./hamster
      run: docker buildx create --name=container --driver=docker-container &&
        docker build -t hamster:test
        --cache-from type=gha,scope=hamster
        --cache-to type=gha,scope=hamster
        --load --builder=container .
    - name: Run container to test
      working-directory: ./hamster
      run: ./test.sh docker
