name: hamster

on:
  workflow_call:  # allow this workflow to be called from other workflows
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_hamster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: ""
        shared-key: v0-rust
        workspaces: |
          hamster -> target
          chamaeleon -> target
    - name: Build
      working-directory: ./hamster
      run: cargo build --verbose
    - name: Run Application Test
      working-directory: ./hamster
      run: ./test.sh
    - name: docker build
      working-directory: ./hamster
      run: docker build -t hamster:test .
    - name: Run container to test
      working-directory: ./hamster
      run: ./test.sh docker
