name: hamster

on:
  workflow_call:  # allow this workflow to be called from other workflows
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_hamster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: shared
        # hamster and chamaeleon share a cache -> only chamaeleon stores to cache to avoid conflicts
        save-if: "false"
    - name: Build
      run: cargo build --verbose -p hamster
    - name: Run Application Test
      run: ./hamster/test.sh
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: "{context}/hamster/Dockerfile"
        push: false
        load: true
        tags: hamster:test
        cache-from: type=gha,scope=hamster
        cache-to: type=gha,mode=max,scope=hamster
    - name: Run container to test
      working-directory: ./hamster
      run: ./test.sh docker
