name: Helm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_helm:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v4
    - 
      name: Set the Kubernetes context
      uses: azure/k8s-set-context@v4
      with:
        method: service-account
        k8s-url: ${{ secrets.KUBERNETES_URL }}
        k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
    - name: print k8s context
      run: kubectl config get-contexts
    - 
      name: lint helm chart
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: helm lint .
    - 
      name: helm dry run
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: helm install --dry-run --debug devnotes-test .
