# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: papagei

on:
  workflow_call:  # allow this workflow to be called from other workflows
  pull_request:
    branches: [ "main" ]

jobs:
  lint_html_papagei:
    name: lint HTML papagei
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install linter
        run: 
          npm install @linthtml/linthtml --save-dev
      - name: lint html
        working-directory: ./papagei
        run:
          npx linthtml 'index.html'
          
          
      
  lint_js_papagei:
    name: lint JS papagei
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install linter
        working-directory: ./papagei
        run:
          npm install eslint
      - name: lint JS
        working-directory: ./papagei/assets
        run:
          npx eslint index.js

  lint_css_papagei:
    name: lint CSS papagei
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install linter
        working-directory: ./papagei
        run: 
          npm init stylelint          
      - name: lint CSS
        working-directory: ./papagei/assets
        run:
          npx stylelint "**/*.css"
