name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
    
  test_chamaeleon:
    uses: ./.github/workflows/chamaeleon.yml  # use the callable tests job to run tests
  test_hamster:
    uses: ./.github/workflows/hamster.yml  # use the callable tests job to run tests

  pub_chamaeleon:
    runs-on: ubuntu-latest
    needs: [test_chamaeleon]
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: "./chamaeleon/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chamaeleon:latest
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha,scope=chamaeleon
          cache-to: type=gha,mode=max,scope=chamaeleon
          
  pub_hamster:
    runs-on: ubuntu-latest    
    needs: [test_hamster]
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: "./hamster/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hamster:latest
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha,scope=hamster
          cache-to: type=gha,mode=max,scope=hamster
