name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    
  test_chamaeleon:
    uses: ./.github/workflows/chamaeleon.yml  # use the callable tests job to run tests
  test_hamster:
    uses: ./.github/workflows/hamster.yml  # use the callable tests job to run tests
  lint_and_test_fuchs:
    uses: ./.github/workflows/fuchs.yml
    secrets: inherit

  build_images:
    strategy:
      matrix:
        platform:
        - runner: ubuntu-latest
          name: amd64
        - runner: ubuntu-24.04-arm
          name: arm64
        service:
        - chamaeleon
        - hamster
        - fuchs
    runs-on: "${{ matrix.platform.runner }}"
    needs: ["test_chamaeleon", "test_hamster", "lint_and_test_fuchs"]
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build image to cache
      uses: docker/build-push-action@v6
      with:
        file: "./${{ matrix.service }}/Dockerfile"
        push: false
        outputs: type=cacheonly
        platforms: linux/${{ matrix.platform.name }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:buildcache-${{ matrix.platform.name }}
        cache-to: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:buildcache-${{ matrix.platform.name }}
  
  publish_images:
    strategy:
      matrix:
        service:
        - chamaeleon
        - hamster
        - fuchs
    runs-on: ubuntu-latest
    needs: [build_images]
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build from cache and push
      uses: docker/build-push-action@v6
      with:
        file: "./${{ matrix.service }}/Dockerfile"
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
        platforms: linux/arm64,linux/amd64
        cache-from: |
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:buildcache-arm64
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:buildcache-amd64
