name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  
  test_services:
    uses: ./.github/workflows/fuchs.yml
    secrets: inherit
  test_papagei: #don't know for what this is needed ad the moment
    uses: ./.github/workflows/papagei.yml  # use the callable tests job to run tests

  build_images:
    strategy:
      matrix:
        platform:
        - runner: ubuntu-latest
          name: amd64
        - runner: ubuntu-24.04-arm
          name: arm64
        service:
        - chamaeleon
        - hamster
        - fuchs
    runs-on: "${{ matrix.platform.runner }}"
    needs: ["test_services"]
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build image to cache
      uses: docker/build-push-action@v6
      with:
        file: "./${{ matrix.service }}/Dockerfile"
        push: false
        outputs: type=cacheonly
        platforms: linux/${{ matrix.platform.name }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:buildcache-${{ matrix.platform.name }}
        cache-to: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:buildcache-${{ matrix.platform.name }}
  
  publish_images:
    strategy:
      matrix:
        service:
        - chamaeleon
        - hamster
        - fuchs
    runs-on: ubuntu-latest
    needs: [build_images]
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build from cache and push
      uses: docker/build-push-action@v6
      with:
        file: "./${{ matrix.service }}/Dockerfile"
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
        platforms: linux/arm64,linux/amd64
        cache-from: |
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:buildcache-arm64
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:buildcache-amd64
  
  deploy:
    runs-on: ubuntu-latest
    needs: [publish_images]
    steps:
      - uses: actions/checkout@v4
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: deploy to k8s cluster
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade devnotes . --install --atomic --namespace=dhge
