name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./chamaeleon
      run: cargo build --verbose
    - name: Run Unit Test
      working-directory: ./chamaeleon
      run: cargo test --verbose
    - name: Run Application Test
      working-directory: ./chamaeleon
      run: ./test.sh

