openapi: 3.1.0
info:
  title: Chamaeleon
  version: "0.1.0"
paths:
  /:
    post:
      summary: convert markdown to html
      operationId: convertMd
      requestBody:
        description: markdown to convert
        content:
          'text/plain':
            schema:
              type: string
      responses:
        '200':
          description: converted text
          content:
            'text/html':
              schema:
                type: string
